run:
  tests: false
  modules-download-mode: readonly
  allow-parallel-runners: true
  go: '1.24'
output:
  sort-results: true
linters-settings:
  gosec:
    excludes:
      # Оно не используется для повышения безопасности или каких-то таких секъюрных вещей, оно используется для выборки
      # произвольного элемента из массива, так что ИДИ НАХУЙ с этой проверкой и не еби мозги липовой безопасностью.
      - G404 # Insecure random number source (rand)
issues:
  exclude-dirs:
    - data
    - vendor
linters:
  disable-all: true
  enable:
    - copyloopvar
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - asasalint
    - asciicheck
    - bodyclose
    - containedctx
    - contextcheck
    - decorder
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - ginkgolinter
    - gocheckcompilerdirectives
    - gocritic
    - godot
    - gofmt
    - goimports
    - gosec
    - gosmopolitan
    - grouper
    - importas
    - ireturn
    - makezero
    - mirror
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - nonamedreturns
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - stylecheck
    - unconvert
    - wastedassign
    - whitespace
    - wsl
